# Generated by Django 3.1.5 on 2021-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=10)),
                ('projectname', models.CharField(max_length=10)),
                ('projectdetails', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('projectname', models.CharField(max_length=10)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0, unique=True)),
                ('username', models.CharField(max_length=10)),
                ('useraddress', models.CharField(max_length=50)),
                ('usercontactnumber', models.IntegerField(default=999)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactAddress',
        ),
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
